### ISSUE TITLE
License inconsistency

### ISSUE THREAD

**Issue by hyandell** [bsorrentino/maven-annotation-plugin#105]
Following up on #68 - I noticed the following subdirectory has an LGPL-3.0 license/source headers. They are your copyright. Should they be considered MIT, or was it intentional for this piece to remain LGPL-3.0?

https://github.com/bsorrentino/maven-annotation-plugin/tree/master/processor

Happy to open a pull request if change is warranted :)

**Comment by bsorrentino** [comment]
Hi @hyandell thanks for feedback 

Should be considered MIT, I'll wait the PR 🙂

**Comment by hyandell** [comment]
Thanks :) Please see #106

**Comment by bsorrentino** [comment]
Hi @hyandell thank you again for contribution
