### ISSUE TITLE
skip execution for projects with packaging pom

### ISSUE THREAD

**Issue by GoogleCodeExporter** [bsorrentino/maven-annotation-plugin#17]
```
What steps will reproduce the problem?
1. Create a multi module project.
2. Configure the maven-annotation-plugin in the parent POM

What is the expected output? What do you see instead?

We get a build error because there is no source directory and no source files 
in the parent POM 
module. That's the case for every module with packaging pom it would in your 
view make sense 
to skip execution for such projects.

Please provide any additional information below.

We configure the maven-annotation-plugin in the parent POM because we want to 
execute it for 
every module.

Attached you'll find a simple patch that implements this.
```

Original issue reported on code.google.com by `philippe...@gmail.com` on 11 Apr 2010 at 6:53

Attachments:
- [maven-processor-plugin.patch](https://storage.googleapis.com/google-code-attachments/maven-annotation-plugin/issue-17/comment-0/maven-processor-plugin.patch)

**Comment by dholzenburg** [comment]
Hi,

I would appreciate an option like <skipPom> to override the default behaviour.
I have a pom-project, but would like the annotation processors to run anyway.

What do you think?

Best regards, Dirk

**Comment by dholzenburg** [comment]
...option like skipPom...

**Comment by bsorrentino** [comment]
Hi the `skip` parameters is already there 

take a look [here](http://bsorrentino.github.io/maven-annotation-plugin/process-mojo.html#skip)
