### ISSUE TITLE
Compiler arguments with spaces

### ISSUE THREAD

**Issue by aleskurlovich** [bsorrentino/maven-annotation-plugin#62]
Hello

This is how we use it:

```
<plugin>
 <groupId>org.bsc.maven</groupId>
    <artifactId>maven-processor-plugin</artifactId>
    <executions>
        <execution>
            <id>eclipselink-jpa-metamodel</id>
            <goals>
                <goal>process</goal>
            </goals>
            <configuration>
                <compilerArguments>
                    -Aeclipselink.persistencexml=${basedir}/src/main/resources/META-INF/persistence.xml
                </compilerArguments>
                <processors>
                    <processor>org.eclipse.persistence.internal.jpa.modelgen.CanonicalModelProcessor
                    </processor>
                </processors>
            </configuration>
        </execution>
    </executions>
    <dependencies>
        <dependency>
            <groupId>org.eclipse.persistence</groupId>
            <artifactId>org.eclipse.persistence.jpa.modelgen.processor</artifactId>
            <version>${eclipselink.version}</version>
            <scope>compile</scope>
        </dependency>
    </dependencies>
</plugin>
```

The problem is that when ${basedir} includes spaces only last part of directory name will be used.
For example, C:\My project\src\main\resources\META-INF\persistence.xml will be used as project\src\main\resources\META-INF\persistence.xml.

**Comment by bsorrentino** [comment]
Hi 

I'll check soon

have you tried : ```-Aeclipselink.persistencexml="${basedir}/src/main/resources/META-INF/persistence.xml"```

**Comment by bsorrentino** [comment]
Hi 

I've checked the implementation and i just pass the ```compilerArguments``` to the compiler.

My thought is that the solution suggested above should work, let me know if it is so  

**Note:**

> Instead of ```compilerArguments``` use ```options``` that make your configuration more clear

>```xml
<options>
 <eclipselink.persistencexml>'${basedir}/src/main/resources/META-INF/persistence.xml'</eclipselink.persistencexml>
</options>
```

**Comment by ChrisWilcox78** [comment]
Just a quick note on this one: wrapping the compiler arguments value in double quotes does not work but adding the options entry does (it looks like you don't even need the quotes in that case).
