### ISSUE TITLE
-sourcepath is not configured

### ISSUE THREAD

**Issue by htfv** [bsorrentino/maven-annotation-plugin#63]
I'm writing an annotation processor which reads the source files using `processingEnv.getFiler().getResource(StandardLocation.SOURCE_PATH, ...)`. It works if annotations are processed with m-compiler-p, but it does not work with m-annotation-p because it does not add the `-sourcepath` option to the compiler.

Possible workaround is to add the `-sourcepath` option manually through the `compilerArguments` property. It would be nice if the plugin could add all source roots automatically.

**Comment by bsorrentino** [comment]
Hi 

You right, i'll add `sourcepath` support asap

**Comment by bsorrentino** [comment]
I've released `3.2.0-SNAPSHOT` with fix 

Please test it and let me know

Thanks in advance

**Comment by htfv** [comment]
Thank you for the quick fix and sorry for the late response.

Unfortunately, it does not work correctly. `-sourcepath` should be the list of source directories, not the compile classpath. m-compiler-p sets this parameter to `compileSourceRoots` + `generatedSourcesDirectory`.

**Comment by bsorrentino** [comment]
Yes ... I miss this detail :-(

I'll fix it very soon

**Comment by bsorrentino** [comment]
I've released a new 3.2.0-SNAPSHOT with fix

Please,  test it and let me know

Thanks in advance

**Comment by htfv** [comment]
It works now! Many thanks!

**Comment by bsorrentino** [comment]
Thank you too

I'll arrange a new release soon

**Comment by bsorrentino** [comment]
version `3.2.0` released
