### ISSUE TITLE
Add option to fork for JDK9 support

### ISSUE THREAD

**Issue by beikov** [bsorrentino/maven-annotation-plugin#64]
I just ran into an issue with this plugin and JDK 9. One of my annotation processors uses a module that isn't visible by default, thus I have to add the module via command line flags. Apparently the module is not picked up by javac if it's running in the same JVM so creating a forked javac would solve the issue.

Can you provide a <fork> option similar to what other plugins provide?

**Comment by beikov** [comment]
Note that a workaround is to add the modules to `MAVEN_OPTS` and also via `compilerArguments`.

**Comment by bsorrentino** [comment]
Hi, thank for feedbacks

Interesting topic ....probably the issue could be solved adding a new _ad-hoc_ argument

what do you think about ?

**Comment by beikov** [comment]
I'm not sure what you mean by _ad hoc_ argument. Could you elaborate?

**Comment by bsorrentino** [comment]
I mean a new **configuration tag** in your case  **fork** (`<fork>true</fork>`) like for example the `maven-compiler-plugin`

However i suppose that you for **module** mean a **jar**, if it is so, have you tried to add it as plugin and/or project dependency ?

**Comment by beikov** [comment]
No what I mean in the JDK 9 sense are modules available on the module path like e.g. **java.xml.bind**.
The `<fork>true</fork>` tag is exactly what is needed!

**Comment by bsorrentino** [comment]
Hi 
I've deployed version `3.3-SNAPSHOT` with support of `fork` property

If you have chance to test it,  I really appreciate that

Thanks in advance

**Comment by bsorrentino** [comment]
released in version `3.3`
