### ISSUE TITLE
(use -source 8 or higher to enable lambda expressions)

### ISSUE THREAD

**Issue by RobertPaasche** [bsorrentino/maven-annotation-plugin#66]
With Version 3.3 we get the error on entities containing lambda expressions.
With 3.2.0 no error occurs.

**Comment by bsorrentino** [comment]
Hi thanks for feedback

I'll check soon. 

Q: Have you using a `toolchain plugin`?
Q: Have you used the new `fork` property ?
Q: Could you test using `maven.compiler.source` and `maven.compiler.target` set to `1.8` ?

**Comment by bsorrentino** [comment]
fix released in version `3.3.1`
