### ISSUE TITLE
Multiple executions of plugin

### ISSUE THREAD

**Issue by beikov** [bsorrentino/maven-annotation-plugin#72]
I'm having this issue that the plugin is executed multiple times. Do you maybe know what the reason for that could be? I'm currently debugging but any hints are very much appreciated.

**Comment by bsorrentino** [comment]
could you give me more details about ?

**Comment by beikov** [comment]
After some debugging, finally figured out the reason with some help of this blog post: http://blog.peterlynch.ca/2010/05/maven-how-to-prevent-generate-sources.html
Apparently, the default configuration of the sources plugin doesn't play nice with plugins bound to the `generate-sources` phase

**Comment by bsorrentino** [comment]
Interesting note ... have you applied the suggestion from blog ?

**Comment by beikov** [comment]
Yes and it works as expected. You might want to add that to the README as I was aware of this problem for a while but only now fixed it.

**Comment by bsorrentino** [comment]
yes I'll do, thanks again.

**Comment by bsorrentino** [comment]
refers to [http://bsorrentino.github.io/maven-annotation-plugin/qa.html]
