### ISSUE TITLE
conflict with org.codehaus.mojo build-helper-maven-plugin

### ISSUE THREAD

**Issue by Ricord** [bsorrentino/maven-annotation-plugin#76]
I use build-helper-maven-plugin to add some sources folder and make it running at `<phase>generate-sources</phase>`. 
while maven-annotation-plugin set phase to process-sources. and set `<additionalSourceDirectories>`, then it **can not**  find the sources in other folder. 
like that:

 ```
error: cannot find symbol
public abstract class MyMessages implements CommonMessages {
                                                ^
  symbol: class CommonMessages 
```

**Comment by bsorrentino** [comment]
Hi could you be more detailed?

The plugin doesn’t find the sources added from build-helper or from additionalsourcedirectory?

**Comment by bsorrentino** [comment]
close for inactivity
