### ISSUE TITLE
Is there a way to stop execution when there is no changes in sources since previous plugin run?

### ISSUE THREAD

**Issue by arkgrudz** [bsorrentino/maven-annotation-plugin#77]
Let's imagine project with around 60 modules. Some of them uses processor plugin to generate xml file (about 20 modules). 

There is a common situation that - during development - only a few classess are changed since previous 'maven install'. In such case, it is highly desirable to do not run annotation processing on modules that there is no changes in the code (and xml file is already created). 

Is there a way to skip annotation processing when certain conditions are meet?

**Comment by bsorrentino** [comment]
Hi @arkgrudz 

I understand your problem ... the plugin has a `skip` property but it is not constrained by any condition.

I don't think that this problem concerns plugin but rather the **processor implementation**

**Comment by arkgrudz** [comment]
Thanks for a quick reply, I really appreciate your work on this plugin. It simply does the job!
I will check the possibilities and let you know what will come out of it.

**Comment by dashorst** [comment]
I think this issue can be closed now that 4.3 is out 👯
