### ISSUE TITLE
Specifying a set of projects instead of qualified class names

### ISSUE THREAD

**Issue by Koldar** [bsorrentino/maven-annotation-plugin#78]
Hi,

I wondered if it is possible to specify a set of maven modules, each containing several processors, instead of having to manually list each processor fully qualified name.

In concrete, instead of having:

```
<processors>
 <processor>a.b.c.d</processor>
 <processor>a.b.c.e</processor>
</processors>
```

It is possible to have:

```
<processors>
 <processorModule>
  <groupId>a.b</groupid>
   <artifactId>c</artifactId>
   <version>1.0</version>
 </processorModule>
 <processorModule>
  <groupId>a.b</groupid>
  <artifactId>c</artifactId>
  <version>1.0</version>
 </processorModule>
</processors>
```

Is it possible to configure the plugin like that? Thanks

**Comment by bsorrentino** [comment]
hi @Koldar 

It is not mandatory to specify a processor (full qualified name ). If you remove it a `default discovery mechanism` will be used based on SPI ( Service Provider Interface).

So what that you ask is possible to achieve adding you module directly into standard maven dependencies and if you don't want to bundle them with your software mark them as optional

**Comment by bsorrentino** [comment]
closed due inactivity
