### ISSUE TITLE
4.5-jdk8 --release flag

### ISSUE THREAD

**Issue by CatalinButaru** [bsorrentino/maven-annotation-plugin#94]
I am getting this error when using release 4.5 with jdk8 compatibility

`[Error] Failed to execute goal org.bsc.maven:maven-processor-plugin:4.5-jdk8:process (generate-immutables-0) on project test: Error executing: invalid flag: --release ->[Help 1]`

Can --release option be conditional on maven.compiler source and target properties, similar to https://github.com/bsorrentino/maven-annotation-plugin/issues/82 ?

**Comment by bsorrentino** [comment]
Hi @CatalinButaru 

Sure, it must be so. Thanks for feedback I'll fix asap

**Comment by bsorrentino** [comment]
Hi @CatalinButaru, please could you check against the last `5.0-jdk8-rc1` release ?

**Comment by CatalinButaru** [comment]
Excellent work. Thank you !
