### ISSUE TITLE
Is this plugin supposed to work with Lombok?

### ISSUE THREAD

**Issue by balloman** [bsorrentino/maven-annotation-plugin#98]
I've spent the past three or four hours, trying to troubleshoot this, but I can't figure it out. Does this plugin support Lombok? 

I have my pom.xml setup like this, but no matter what I do, I can't get it to actually generate from any of the Lombok annotations. Any ideas? Changing the scope doesn't seem to work either.
```
<plugin>
<groupId>org.bsc.maven</groupId>
<artifactId>maven-processor-plugin</artifactId>
<version>5.0-rc2</version>
<executions>
	<execution>
		<id>process</id>
		<goals>
			<goal>process</goal>
		</goals>
		<phase>generate-sources</phase>
		<configuration>
			<processors>
				<processor>lombok.launch.AnnotationProcessorHider$AnnotationProcessor</processor>
			</processors>
		</configuration>
	</execution>
</executions>
<dependencies>
	<dependency>
		<groupId>org.projectlombok</groupId>
		<artifactId>lombok</artifactId>
		<version>${lombok.version}</version>
		<scope>runtime</scope>
	</dependency>
</dependencies>
</plugin>
```

**Comment by bsorrentino** [comment]
Hi @balloman thank for using this project

Such issue concerns the fact that `processor plugin` seems not able to process the Lombok annotations ? Is it so ?
