### ISSUE TITLE
Parse Java 17 source code

### ISSUE THREAD

**Issue by cpfeiffer** [bsorrentino/maven-annotation-plugin#99]
I tried maven-processor-plugin on source code using Java 17 features (records, sealed classes, instanceof expressions, multiline strings, ...) and it failed to parse any of it.

Are there any plans to support this in the future?

**Comment by bsorrentino** [comment]
Hi @cpfeiffer thanks for feedback 

I'll work on it 👍

**Comment by cpfeiffer** [comment]
Hi @bsorrentino, I think I was wrong.  When looking at the source of your plugin, I found the properties `maven.processor.source` and `maven.processor.target`. Setting these to `17` makes it work already.

Thanks :smile:

**Comment by bsorrentino** [comment]
Hi @cpfeiffer 

This was stated also in `processor:process` goal's documentation [here](http://bsorrentino.github.io/maven-annotation-plugin/process-mojo.html#fork)

**Comment by cpfeiffer** [comment]
Thanks! One last thing to add (although out of scope for this plugin), is that these properties have no effect when invoked from m2e (via [m2e-apt](https://github.com/jbosstools/m2e-apt)). So m2e-apt has to be configured to use JDT APT instead of invoking maven-processor-plugin.

**Comment by bsorrentino** [comment]
Unfortunately I'm no so expert in use of JDT APT  however you can try to use properties combined with `<fork>true</true>` to test if they have effect
